import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { getServerSession } from "next-auth";

import { cn } from "@/lib/utils";
import { prisma } from "@/lib/prisma";
import { authOptions } from "@/auth";

import Navbar from "./components/Navbar";
import SessionProvider from "./SessionProvider";
import Footer from "./components/Footer";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);
      let cartItemsCount = 0;
       if (session?.user?.email) {
    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
      include: {
        cart: {
          include: {
            items: true,
          },
        },
      },
    });
  
    cartItemsCount =
      user?.cart?.items.reduce((total, item) => total + item.quantity, 0) ?? 0;
  }
  


  return (
    <html
      lang="fr"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">
        <SessionProvider>
          <Navbar  cartItemsCount={cartItemsCount}/>
          {children}
          <Footer/>
        </SessionProvider>
      </body>
    </html>
  );
}
